version: '3.8'

services:
  nmap:
    build: .
    container_name: nmap
    volumes:
      - ./listado.list:/listado.list

    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_USER=nmap_user
      - INFLUXDB_PASSWORD=beonitdemo
      - INFLUXDB_DB=nmap
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=nmap
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=beonitdemo
      - INFLUXDB_USER=nmap_user
      - INFLUXDB_USER_PASSWORD=beonitdemo
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/grafana/grafana.crt
      - GF_SERVER_CERT_KEY=/etc/grafana/grafana.key
      - GF_INSTALL_PLUGINS=grafana-polystat-panel,alexanderzobnin-zabbix-app # Plugins a instalar
      - GF_SERVER_ROOT_URL=https://13.77.124.144:3000/ # URL base de Grafana
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana
      - ./mycert.crt:/etc/grafana/grafana.crt
      - ./private.key:/etc/grafana/grafana.key

volumes:
  influxdb_data:
  grafana_data:
