version: '3.8'

services:
  nmap:
    build: .
    container_name: nmap
    volumes:
      - ./listado.list:/listado.list
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=nmap_user
      - MYSQL_PASSWORD=B3on1TD3mo
      - MYSQL_DB=nmap
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=B3on1TD3mo
      - MYSQL_DATABASE=nmap
      - MYSQL_USER=nmap_user
      - MYSQL_PASSWORD=B3on1TD3mo
    volumes:
      - mysql_data:/var/lib/mysql

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/grafana/grafana.crt
      - GF_SERVER_CERT_KEY=/etc/grafana/grafana.key
      - GF_INSTALL_PLUGINS=grafana-polystat-panel,alexanderzobnin-zabbix-app # Plugins a instalar
      - GF_SERVER_ROOT_URL=https://13.77.124.144:3000/ # URL base de Grafana
    depends_on:
      - mysql
    volumes:
      - grafana_data:/var/lib/grafana
      - ./mycert.crt:/etc/grafana/grafana.crt
      - ./private.key:/etc/grafana/grafana.key

volumes:
  mysql_data:
  grafana_data:
